### ISSUE TITLE
create issue from comment

### ISSUE THREAD

**Issue by bscofield** [githuba11y/repo_the_second2#120]
Quam inventore ea. Quam voluptatem quis. Vel vero molestiae.

**Comment by alebourne** [comment]
Types of whales
There are two types of whales: toothed and baleen. Toothed whales, as the name suggests, have teeth, which are used to hunt and eat squid, fish, and seals. Toothed whales include sperm whales, as well as dolphins, porpoises, and orcas, among others. The narwhal’s “horn” is actually one long tooth protruding through its lip.

**Comment by alebourne** [comment]
> Types of whales
> There are two types of whales: toothed and baleen. Toothed whales, as the name suggests, have teeth, which are used to hunt and eat squid, fish, and seals. Toothed whales include sperm whales, as well as dolphins, porpoises, and orcas, among others. The narwhal’s “horn” is actually one long tooth protruding through its lip.

What interesting information
